### PR TITLE
Added Chat Bot

### PR DESCRIPTION
**Pull request by areeburrub**
Add a Chat bot ( #2 )
Task of Adding a Chat Bot to this website was assigned to me I have added it and created this pull request.

### How it is working
The Chat bot is working on Google Dialog Flow which enables it to interact with user naturally. I have used an external API to get the data for the chatbot.

To get more details and credentials of API and DialogFlow Account Admin can contact me on - areeburrub@gmail.com

### CODE REVIEW

**Comment by areeburrub** [comment]
Can anyone Explain me why these checks are getting failed, my project is working locally.

**Comment by TheTeamEngineer** [comment]
@areeburrub  your pr have a conflict with the main branch kindly check it, also include a screenshot

**Comment by areeburrub** [comment]
ScreenShot
Demo : https://deploy-preview-8--electrotech1.netlify.app/

**Comment by areeburrub** [comment]
Please give me the list of questions so that I can add answer to them

**Comment by areeburrub** [comment]
Please give me the LEVEL tag on this PR as instructed by the GsSOC Discord Server
image

**Pull request merged**
