### PR TITLE
solves #51

### PR DESCRIPTION
**Pull request by srivastavaritik**
solves #51 .
<h1>Before</h1>
image
image
image
image
<h1>After</h1>
image
image
image
image

### CODE REVIEW

**Comment by srivastavaritik** [comment]
Please assign this gssoc label as this pr is not showing on gssoc leaderboard

**Comment by srivastavaritik** [comment]
please add gssoc label

**Comment by gurjeetsinghvirdee** [comment]
Kindly add labels
CC: @Furquan712

**Comment by srivastavaritik** [comment]
@Furquan712 it was level 3 issue

**Comment by gurjeetsinghvirdee** [comment]
@Furquan712 that labels are incorrect 
please fix it

**` GSSoC22`**  **`Level3`** use these labels

**Comment by srivastavaritik** [comment]
@Furquan712 the labels you added are wrong, its not showing on the leaderboard. It should be Level3 instead of level 3

**Comment by srivastavaritik** [comment]
@Furquan712 sir, you are writing the labels wrong, there is no space between Level and 3 and L is capital letters. It should be **Level3**

**Comment by gurjeetsinghvirdee** [comment]
@Furquan712 Fix your labels like this
Screenshot 2022-05-28 121328

**Comment by srivastavaritik** [comment]
> @Furquan712 Fix your labels like this Screenshot 2022-05-28 121328

@gurjeetsinghvirdee sir please look into this, as my total time that I invested in this issue will be waste as the GSSoC is near to end and points are not showing on leader board. Please ask @Furquan712 to correct this asap.

**Comment by gurjeetsinghvirdee** [comment]
@srivastavaritik Already mentioned in discord and send a DM but no response

**Pull request merged**
